<?php
const DEMO_NEJ_EYOTA = [
  'OD_Common_Eyota' => 1,
  'OD_Common_Nausicaa' => 2,
  'OD_Rare_Nausicaa' => 2,
  'OD_Common_ShipSecurityOfficer' => 2,
  'OD_Rare_ShipSecurityOfficer' => 2,
  'OD_Common_MajesticEagle' => 2,
  'OD_Rare_MajesticEagle' => 2,
  'OD_Common_Paris' => 2,
  'OD_Rare_Paris' => 2,
  'OD_Common_TriremeQuartermaster' => 2,
  'OD_Rare_TriremeQuartermaster' => 2,
  'OD_Exalted_AthenaGoddessofStrategy' => 2,
  'OD_Exalted_TheHomer' => 2,
  'OD_Common_Troy' => 2,
  'OD_Rare_Troy' => 2,
  'OD_Common_TheTrojanHorse' => 2,
  'OD_Rare_TheTrojanHorse' => 2,
  'OD_Common_MenelausBringerofWar' => 2,
  'OD_Rare_MenelausBringerofWar' => 2,
  'OD_Common_HelenofTroy' => 2,
  'OD_Rare_HelenofTroy' => 2,
  'OD_Common_OrdisGeneral' => 2,
  'OD_Rare_OrdisGeneral' => 2,
  'OD_Common_OrdisCounterspy' => 2,
  'OD_Rare_OrdisCounterspy' => 2,
  'OD_Common_Hector' => 2,
  'OD_Rare_Hector' => 2,
  'OD_Common_StrengthinNumbers' => 2,
  'OD_Rare_StrengthinNumbers' => 2,
  'OD_Common_EchoChamber' => 2,
  'OD_Rare_EchoChamber' => 2,
  'OD_Common_BlindingBlow' => 2,
  'OD_Rare_BlindingBlow' => 2,
];
?>
