<?php
const DEMO_NEJ_GRAY = [
  'YZ_Common_Gray' => 1,
  'YZ_Common_MoltedMaw' => 1,

  'YZ_Common_FleeingGoose' => 2,
  'YZ_Rare_FleeingGoose' => 2,
  'YZ_Common_OfferingtotheGods' => 2,
  'YZ_Rare_OfferingtotheGods' => 2,
  'YZ_Common_CassandraCursedProphetess' => 2,
  'YZ_Rare_CassandraCursedProphetess' => 2,
  'YZ_Common_Polyxena' => 2,
  'YZ_Rare_Polyxena' => 2,
  'YZ_Common_PenelopesSuitors' => 2,
  'YZ_Rare_PenelopesSuitors' => 2,
  'YZ_Common_QorganIntelligencer' => 2,
  'YZ_Rare_QorganIntelligencer' => 2,
  'YZ_Common_Circe' => 2,
  'YZ_Rare_Circe' => 2,
  'YZ_Common_Agamemnon' => 2,
  'YZ_Rare_Agamemnon' => 2,
  'YZ_Common_Siren' => 2,
  'YZ_Rare_Siren' => 2,
  'YZ_Common_WaveAway' => 2,
  'YZ_Rare_WaveAway' => 2,
  'YZ_Common_TheCrash' => 2,
  'YZ_Rare_TheCrash' => 2,
  'YZ_Common_Iphigenia' => 2,
  'YZ_Rare_Iphigenia' => 2,
  'YZ_Common_MawsMolting' => 2,
  'YZ_Rare_MawsMolting' => 2,
  'YZ_Common_BetweenaRockandaHardPlace' => 2,
  'YZ_Rare_BetweenaRockandaHardPlace' => 2,
  'YZ_Common_FaneofIthaca' => 2,
  'YZ_Rare_FaneofIthaca' => 2,
  'YZ_Exalted_HermesGodofSouls' => 2,
  'YZ_Exalted_TreacherousLoop' => 2,
];
?>
