<?php
const DEMO_NEJ_KOJO = [
  'BR_Common_SquireKojo' => 1,
  'BR_Common_BlazingBooda' => 1,

  'BR_Common_ChargingRam' => 2,
  'BR_Rare_ChargingRam' => 2,
  'BR_Common_Patroclus' => 2,
  'BR_Rare_Patroclus' => 2,
  'BR_Common_AltrunLinebacker' => 2,
  'BR_Rare_AltrunLinebacker' => 2,
  'BR_Common_Telemachus' => 2,
  'BR_Rare_Telemachus' => 2,
  'BR_Common_TriremeCaptain' => 2,
  'BR_Rare_TriremeCaptain' => 2,
  'BR_Common_Eurylochus' => 2,
  'BR_Rare_Eurylochus' => 2,
  'BR_Common_HerostratusBurnerofTemples' => 2,
  'BR_Rare_HerostratusBurnerofTemples' => 2,
  'BR_Common_HearthJinn' => 2,
  'BR_Rare_HearthJinn' => 2,
  'BR_Common_RinkuAltrunAce' => 2,
  'BR_Rare_RinkuAltrunAce' => 2,
  'BR_Common_BravosSteward' => 2,
  'BR_Rare_BravosSteward' => 2,
  'BR_Common_Polyphemus' => 2,
  'BR_Rare_Polyphemus' => 2,
  'BR_Common_Ajax' => 2,
  'BR_Rare_Ajax' => 2,
  'BR_Common_ClashofCombatants' => 2,
  'BR_Rare_ClashofCombatants' => 2,
  'BR_Common_ShowofStrength' => 2,
  'BR_Rare_ShowofStrength' => 2,
  'BR_Common_FaneoftheCyclopes' => 2,
  'BR_Rare_FaneoftheCyclopes' => 2,
  'BR_Exalted_HestiaGoddessoftheHearth' => 2,
  'BR_Exalted_Charybdis' => 2,
];
?>
