<?php
const DEMO_NEJ_OSRIC = [
  'MU_Common_Osric' => 1,
  'MU_Common_Toot' => 1,

  'MU_Common_FaithfulDog' => 2,
  'MU_Rare_FaithfulDog' => 2,
  'MU_Common_Silenus' => 2,
  'MU_Rare_Silenus' => 2,
  'MU_Common_Ino' => 2,
  'MU_Rare_Ino' => 2,
  'MU_Common_StockyShroom' => 2,
  'MU_Rare_StockyShroom' => 2,
  'MU_Common_MastTiedOdysseus' => 2,
  'MU_Rare_MastTiedOdysseus' => 2,
  'MU_Common_ParnassusBoar' => 2,
  'MU_Rare_ParnassusBoar' => 2,
  'MU_Common_Eumaeus' => 2,
  'MU_Rare_Eumaeus' => 2,
  'MU_Common_HellequinTrapper' => 2,
  'MU_Rare_HellequinTrapper' => 2,
  'MU_Common_CalypsoBenevolentJailor' => 2,
  'MU_Rare_CalypsoBenevolentJailor' => 2,
  'MU_Common_FamedMycologist' => 2,
  'MU_Rare_FamedMycologist' => 2,
  'MU_Common_HornofPlenty' => 2,
  'MU_Rare_HornofPlenty' => 2,
  'MU_Common_SheepThrill' => 2,
  'MU_Rare_SheepThrill' => 2,
  'MU_Common_TiedtotheMast' => 2,
  'MU_Rare_TiedtotheMast' => 2,
  'MU_Common_FaneofCalypso' => 2,
  'MU_Rare_FaneofCalypso' => 2,
  'MU_Common_TimeFlies' => 2,
  'MU_Rare_TimeFlies' => 2,
  'MU_Exalted_ArtemisGoddessoftheHunt' => 2,
  'MU_Exalted_Scylla' => 2,
];
?>
