<?php
const DEMO_NEJ_ZOE = [
  'LY_Common_Zoe' => 1,
  'LY_Common_Shift' => 1,

  'LY_Common_UnstudiousPig' => 2,
  'LY_Rare_UnstudiousPig' => 2,
  'LY_Common_ReefDolphin' => 2,
  'LY_Rare_ReefDolphin' => 2,
  'LY_Common_ScheriasRoyalty' => 2,
  'LY_Rare_ScheriasRoyalty' => 2,
  'LY_Common_LyraGambler' => 2,
  'LY_Rare_LyraGambler' => 2,
  'LY_Common_DemodocusWeaverofTales' => 2,
  'LY_Rare_DemodocusWeaverofTales' => 2,
  'LY_Common_TumultTamer' => 2,
  'LY_Rare_TumultTamer' => 2,
  'LY_Common_LotusEater' => 2,
  'LY_Rare_LotusEater' => 2,
  'LY_Common_LaestrygonianQueen' => 2,
  'LY_Rare_LaestrygonianQueen' => 2,
  'LY_Common_LyraHighroller' => 2,
  'LY_Rare_LyraHighroller' => 2,
  'LY_Common_DemodocusTale' => 2,
  'LY_Rare_DemodocusTale' => 2,
  'LY_Common_DoubleCross' => 2,
  'LY_Rare_DoubleCross' => 2,
  'LY_Common_EntrancingFragrance' => 2,
  'LY_Rare_EntrancingFragrance' => 2,
  'LY_Common_IffyNavigator' => 2,
  'LY_Rare_IffyNavigator' => 2,
  'LY_Common_FaneofNausicaa' => 2,
  'LY_Rare_FaneofNausicaa' => 2,
  'LY_Common_TriremeTrickster' => 2,
  'LY_Rare_TriremeTrickster' => 2,
  'LY_Exalted_ShrewdOdysseus' => 2,
  'LY_Exalted_DionysosGodofFeasts' => 2,
];
?>
